kind: pipeline
name: default

workspace:
  base: /go
  path: src/github.com/annProg/citest

steps:
- name: build
  image: golang:1.11
  volumes:
  - name: tmp
    path: /build
  commands:
  - go test
  - go build -o main
  - ls
- name: build-image
  image: plugins/docker
  volumes:
  - name: tmp
    path: /build
  settings:
    repo: citest
    auto_tag: true
    dry_run: true
    password:
      from_secret: passwd
  commands:
  - echo "$PLUGIN_REPO"
  - echo "$PLUGIN_AUTO_TAG"
  - echo "$PLUGIN_PASSWD"
  
volumes:
- name: tmp
  temp: {}
