kind: pipeline
name: default

workspace:
  base: /go
  path: src/github.com/annProg/citest

steps:
- name: build
  image: golang:1.11
  volumes:
  - name: docker_sock
    path: /var/run/docker.sock
  commands:
  - go test
  - go build
  
volumes:
- name: docker_sock
  host:
    path: /var/run/docker.sock
- name: tmp
  host:
    path: {}