kind: pipeline
name: default

workspace:
  base: /go
  path: src/github.com/annProg/citest

steps:
- name: build
  image: golang:1.11
  volumes:
  - name: tmp
    path: /build
  commands:
  - go test
  - go build -o citest

- name: release
  image: plugins/github-release
  settings:
    api_key:
      from_secret: github_token
    files: citest
  checksum:
    - sha1
  note: CHANGELOG.md
  when:
    envent: tag
