kind: pipeline
name: default

workspace:
  base: /go
  path: src/github.com/annProg/citest

steps:
- name: build
  image: golang:1.11
  volumes:
  - name: tmp
    path: /data
  commands:
  - go test
  - go build
  
volumes:
- name: tmp
  temp: {}