kind: pipeline
name: default

workspace:
  base: /go
  path: src/github.com/annProg/citest

steps:
- name: build
  image: golang:1.11
  volumes:
  - name: tmp
    path: /data
  commands:
  - go test
  - go build
- name: build-image
  image: plugins/docker
  settings:
    repo: citest
    auto_tag: true
  
volumes:
- name: tmp
  temp: {}