kind: pipeline
name: default

workspace:
  base: /go
  path: src/github.com/annProg/citest

steps:
- name: build
  image: golang:1.11
  volumes:
  - name: tmp
    path: /build
  commands:
  - go test
  - go build -o /build/main
  - ls /build
- name: build-image
  image: plugins/docker
  volumes:
  - name: tmp
    path: /build
  settings:
    repo: citest
    auto_tag: true
  
volumes:
- name: tmp
  temp: {}