name: Test Action

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: uname-a
      run: uname -a
    - name: uname-m
      run: uname -m
    - name: docker
      run: docker version
    - name: docker-info
      run: docker info
    - name: df
      run: df -h
    - name: free
      run: free -m
    - name: cpu
      run: cat /proc/cpuinfo
    - name: pwd
      run: pwd
    - name: ls
      run: ls / -l
    - name: ip
      run: ifconfig
    - name: release
      run: |
        dd if=/dev/zero of=test_file_20MB bs=1M count=20
        ls -l
        export ID=`curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/repos/arm4rpi/pandoc-deps/releases/tags/v0.1" |grep '"id"' |head -n 1 |awk '{print $2}' |tr -d ','`
        curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -H "Content-Type: $(file -b --mime-type test_file_20MB)" "https://uploads.github.com/repos/arm4rpi/pandoc-deps/releases/$ID/assets?name=test_file_20MB" --data-binary @test_file_20MB
        exit $?
      
